package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"bst-tech/program/graph"
	"bst-tech/program/infra/boiler"
	"context"
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"
)

// GetTask is the resolver for the getTask field.
func (r *queryResolver) GetTask(ctx context.Context, taskID int) (*graph.GetTaskOutput, error) {
	panic(fmt.Errorf("not implemented:  GetTask - getTask"))
}
