version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tech
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tech
    volumes:
      - db-store:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./app/src:/app
volumes:
  db-store:
