// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTaskOutput struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateTaskInput struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}
